### ISSUE TITLE
Get this building using AppVeyor

### ISSUE THREAD

**Issue by superlogical** [serilog/serilog-sinks-amazonkinesis#1]

**Comment by superlogical** [comment]
Hi @nblumhardt 

I've managed to get a successful build :)
[![Build status](https://ci.appveyor.com/api/projects/status/0ry328alcvvykk8m/branch/master?svg=true)](https://ci.appveyor.com/project/superlogical/serilog-sinks-amazonkinesis/branch/master)

Any ideas on how to publish this to NuGet from AppVeyor? Is that how your doing it?

**Comment by superlogical** [comment]
#2 Closes this

**Comment by nblumhardt** [comment]
Still needs some attention, moved to the Serilog tracker here: https://github.com/serilog/serilog/issues/435

We turn off the trackers on each sink repository to keep things manageable in a central way, will turn this one off now too. Cheers!
