### ISSUE TITLE
Current nuget package does not work with ASP.Net Core 2.0 project

### ISSUE THREAD

**Issue by anandja** [serilog/serilog-sinks-amazonkinesis#39]
Looks like the AWSSDK dependencies do not support .Net standard based on the version in nuget. Any estimate on when a latest nuget package will be released with the latest updated .Net Standard support?

**Comment by troylar** [comment]
@anandja Get latest . . .should be fixed now.

**Comment by anandja** [comment]
Thanks. It looks good now.
