### ISSUE TITLE
Avoid file locks for opened files

### ISSUE THREAD

**Issue by masonkmeyer** [serilog/serilog-sinks-amazonkinesis#42]
The RollingFile sink creates a SharedFileSink when you pass the **shared** flag (https://github.com/serilog/serilog/issues/1005). 

Is it possible to add a setting to the KinesisFirehoseSinkOptions to pass a **shared** setting to the underlying RollingFileSink?

It looks like it could be set here: 
https://github.com/serilog/serilog-sinks-amazonkinesis/blob/master/src/Serilog.Sinks.Amazon.Kinesis/Firehose/Sinks/DurableKinesisFirehoseSink.cs#L39

I would be happy to create a PR for this change.

**Comment by troylar** [comment]
Go ahead, I'll take a look.

**Comment by masonkmeyer** [comment]
This change would require an upgrade to some of the packages. It is dependant on #38 being merged (and then some additional package upgrades). I would still like to do it but I understand that it has an effect on the larger community.

**Comment by masonkmeyer** [comment]
Nevermind. I was looking at the dev branch. I will make the change and get a PR for you.

**Comment by mattbeatty** [comment]
@troylar Let me know when you get a chance to check out that PR. :+1:

**Comment by troylar** [comment]
Merged

**Comment by mattbeatty** [comment]
:+1:
